// Start the client on 127.0.0.1:4173 first, then run yarn test:ui
const assert = require('node:assert/strict');
const { mkdir } = require('node:fs/promises');
const { baseURL, chromium, contextOptions, installFixtures } = require('./support/ui-fixtures.cjs');
const { version } = require('../package.json');

(async () => {
    await mkdir('artifacts/v2', { recursive: true });
    const browser = await chromium.launch({ headless: true });
    try {
        const context = await browser.newContext(contextOptions);
        const errors = [];
        const fixture = await installFixtures(context);
        const page = await context.newPage();
        page.on('pageerror', error => errors.push(error.message));
        const preferencesSaved = () => page.waitForRequest(r => r.url().endsWith('/api/accounts/me/preferences') && r.method() === 'PATCH');
        await page.goto(baseURL + '/servers');
        await page.getByRole('heading', { name: 'Infrastructure access' }).waitFor();
        await page.locator('.host-row').first().waitFor();
        await page.evaluate(() => document.fonts.ready);
        assert.equal(await page.locator('.server-list .server-object').count(), 8);
        assert.equal(await page.getByText('Host directory').count(), 0, 'the overview must not duplicate the inventory');
        await page.screenshot({ path: 'artifacts/v2/workspace-dark.png', fullPage: true });
        const search = page.getByRole('textbox', { name: 'Search hosts…' });
        const visibleHosts = async query => {
            await search.fill(query);
            return page.locator('.server-list .server-object').allInnerTexts().then(names => names.map(name => name.trim()));
        };
        let previous = await visibleHosts('');
        for (const query of ['w', 'wi', 'win', 'win-', 'win-a', 'win-admin', 'win-admin-01']) {
            const current = await visibleHosts(query);
            assert.ok(current.every(name => previous.includes(name)), `"${query}" broadened the result`);
            previous = current;
        }
        assert.deepEqual(previous, ['win-admin-01']);
        assert.deepEqual(await visibleHosts('10.24.2.21'), ['core-db-01']);
        assert.equal((await visibleHosts('rdp')).length, 2);
        await visibleHosts('no-such-host');
        await page.getByText('No matching hosts').waitFor();
        await search.fill('');
        await page.locator('.host-row').first().click();
        await page.getByText('Fixture connection unavailable').waitFor();
        assert.equal(fixture.requests.find(r => r.path === '/api/connections').body.identityId, 1);
        await page.locator('.toast-close').click();
        await page.locator('.toast').waitFor({ state: 'hidden' });
        assert.equal(await page.getByText('Pair companion app', { exact: true }).count(), 0);
        const themeSaved = preferencesSaved();
        await page.getByRole('button', { name: 'Switch light / dark theme' }).click();
        await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
        assert.deepEqual((await themeSaved).postDataJSON(), { theme: { mode: 'light' } });
        await page.screenshot({ path: 'artifacts/v2/workspace-light.png', fullPage: true });
        await page.getByRole('button', { name: 'Toggle inventory navigation' }).first().click();
        assert.match(await page.locator('.left-pane').getAttribute('class'), /collapsed/);
        await page.getByRole('button', { name: 'Toggle inventory navigation' }).first().click();
        await page.getByRole('button', { name: 'Connect NetBox', exact: true }).click();
        await page.locator('.dialog-area').waitFor();
        await page.screenshot({ path: 'artifacts/v2/netbox-dialog.png', fullPage: true });
        await page.keyboard.press('Escape');
        await page.locator('.dialog-area').waitFor({ state: 'hidden' });
        await page.getByRole('link', { name: 'Settings', exact: true }).click();
        await page.locator('.administration-index').waitFor();
        await page.screenshot({ path: 'artifacts/v2/administration.png', fullPage: true });
        const logo = await page.locator('.brand-mark svg').boundingBox();
        assert.ok(logo.width >= 40 && Math.abs(logo.width - logo.height) < 1);
        assert.equal(await page.locator('.persistent-server-workspace .welcome-panel').count(), 1);
        await page.locator('.settings-navigation').getByRole('link', { name: 'Authentication', exact: true }).click();
        await page.getByRole('button', { name: 'Add LDAP', exact: true }).click();
        await page.getByRole('button', { name: 'Close dialog', exact: true }).focus();
        await page.keyboard.press('Shift+Tab');
        assert.equal(await page.evaluate(() => document.querySelector('.dialog').contains(document.activeElement)), true);
        await page.keyboard.press('Tab');
        assert.equal(await page.getByRole('button', { name: 'Close dialog', exact: true }).evaluate(el => el === document.activeElement), true);
        await page.getByLabel('Directory domain', { exact: true }).fill('corp.example.com');
        await page.getByRole('button', { name: 'Apply defaults', exact: true }).click();
        assert.equal(await page.getByLabel('Host', { exact: true }).inputValue(), 'ipa.corp.example.com');
        assert.equal(await page.getByLabel('Port', { exact: true }).inputValue(), '636');
        const directory = page.getByLabel('Directory', { exact: true });
        await directory.focus();
        await page.keyboard.press('ArrowDown');
        await page.getByRole('option', { name: 'Microsoft Active Directory' }).waitFor();
        await page.keyboard.press('ArrowDown');
        await page.keyboard.press('Enter');
        assert.equal(await directory.textContent(), 'Microsoft Active Directory');
        await page.getByRole('button', { name: 'Apply defaults', exact: true }).click();
        assert.equal(await page.getByLabel('Host', { exact: true }).inputValue(), 'dc01.corp.example.com');
        await page.getByLabel('Bind password', { exact: true }).fill('fixture-only');
        await page.screenshot({ path: 'artifacts/v2/ldap-preset.png', fullPage: true });
        await page.getByRole('button', { name: 'Test connection', exact: true }).click();
        await page.waitForFunction(() => document.querySelector('.ldap-test-results'));
        assert.equal(fixture.requests.find(r => r.path === '/api/auth/providers/admin/ldap/test').body.host, 'dc01.corp.example.com');
        await page.keyboard.press('Escape');
        await page.getByRole('alertdialog').waitFor();
        await page.screenshot({ path: 'artifacts/v2/unsaved-dialog.png', fullPage: true });
        await page.getByRole('button', { name: 'Keep editing', exact: true }).click();
        assert.equal(await page.locator('.dialog-area').count(), 1);
        await page.keyboard.press('Escape');
        await page.getByRole('button', { name: 'Close without saving', exact: true }).click();
        await page.locator('.dialog-area').waitFor({ state: 'hidden' });
        assert.equal(await page.evaluate(() => document.getElementById('root').inert), false);
        await page.locator('.settings-navigation').getByRole('link', { name: 'Account', exact: true }).click();
        await page.locator('.account-page').waitFor();
        assert.equal(await page.locator('.accent-color-selector').count(), 0);
        await page.screenshot({ path: 'artifacts/v2/account.png', fullPage: true });
        await page.locator('.settings-navigation').getByRole('link', { name: 'Terminal', exact: true }).click();
        await page.locator('.theme-cards').waitFor();
        assert.equal(await page.getByRole('button', { name: /Synced to account|This browser only/ }).count(), 0, 'preferences always follow the account');
        await page.screenshot({ path: 'artifacts/v2/terminal.png', fullPage: true });
        fixture.connectionSucceeds = true;
        await page.locator('.workspace-global-nav').getByRole('link', { name: 'Workspace', exact: true }).click();
        await page.locator('.host-row').first().click();
        await page.locator('.xterm').waitFor();
        await page.locator('.xterm').evaluate(el => el.dataset.fixturePersistent = 'yes');
        const socketsBeforeNavigation = fixture.terminalSockets;
        assert.ok(socketsBeforeNavigation > 0);
        await page.locator('.workspace-global-nav').getByRole('link', { name: 'Settings', exact: true }).click();
        await page.locator('.administration-index').waitFor();
        await page.setViewportSize({ width: 1500, height: 950 });
        await page.locator('.workspace-global-nav').getByRole('link', { name: 'Workspace', exact: true }).click();
        await page.locator('.xterm').waitFor();
        assert.equal(await page.locator('.xterm').getAttribute('data-fixture-persistent'), 'yes');
        assert.equal(fixture.terminalSockets, socketsBeforeNavigation);
        assert.ok(!fixture.terminalMessages.some(message => message === '\x010,0'));
        await page.screenshot({ path: 'artifacts/v2/active-terminal.png', fullPage: true });
        await page.locator('.server-tab').first().click({ button: 'right' });
        await page.getByRole('menuitem', { name: 'Share read-only', exact: true }).hover();
        const shared = page.waitForRequest(r => /\/api\/connections\/[^/]+\/share$/.test(r.url()) && r.method() === 'POST');
        await page.getByRole('menuitem', { name: 'For 8 hours', exact: true }).click();
        assert.deepEqual((await shared).postDataJSON(), { writable: false, hours: 8 });
        await page.getByText(/Anyone with the link can watch this session until/).waitFor();
        fixture.emit('CONNECTION_PROMPT', { id: 'prompt-1', title: 'edge-zrh-01', instructions: 'Duo two-factor login',
            prompts: [{ prompt: 'Verification code: ', echo: false }] });
        await page.getByRole('heading', { name: 'Sign in to edge-zrh-01' }).waitFor();
        await page.getByLabel('Verification code', { exact: true }).fill('123456');
        const answered = page.waitForRequest(r => r.url().endsWith('/api/connections/prompts/prompt-1'));
        await page.getByRole('button', { name: 'Continue', exact: true }).click();
        assert.deepEqual((await answered).postDataJSON(), { answers: ['123456'] });
        await page.getByRole('heading', { name: 'Sign in to edge-zrh-01' }).waitFor({ state: 'detached' });
        fixture.emit('CONNECTION_FAILED', { sessionId: 'x', serverName: 'core-db-01', message: 'The host key of 10.24.2.21:22 has changed' });
        await page.getByText('core-db-01: The host key of 10.24.2.21:22 has changed').waitFor();
        await page.locator('.server-tab').first().click({ button: 'right' });
        await page.getByRole('menuitem', { name: 'File manager', exact: true }).click();
        const fileManager = page.locator('[data-floating-windows] .file-manager-window');
        const fileItem = name => fileManager.locator('.file-item h2', { hasText: name });
        await fileItem('architecture.svg').waitFor();
        assert.equal(await page.evaluate(() => document.getElementById('root').inert), false, 'the workspace stays usable');
        // reduced motion still leaves a tiny transition
        const nextFrame = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
        const managerStart = await fileManager.boundingBox();
        await page.mouse.move(managerStart.x + 200, managerStart.y + 20);
        await page.mouse.down();
        await page.mouse.move(managerStart.x + 100, managerStart.y - 40, { steps: 4 });
        await page.mouse.up();
        await nextFrame();
        const managerMoved = await fileManager.boundingBox();
        assert.ok(managerMoved.x < managerStart.x && managerMoved.y < managerStart.y, 'file manager window is draggable');
        await page.mouse.click(managerMoved.x + managerMoved.width + 60, managerMoved.y + managerMoved.height + 40);
        await page.keyboard.press('Control+A');
        assert.equal(await fileManager.locator('.file-item.selected').count(), 0);
        await fileManager.locator('.address-bar').click();
        assert.equal(await fileManager.locator('.path-input').inputValue(), '/srv/www/');
        await fileManager.locator('.suggestion-item', { hasText: '/srv/www/releases' }).waitFor();
        await page.keyboard.type('.');
        await fileManager.locator('.suggestion-item', { hasText: '/srv/www/assets' }).waitFor({ state: 'detached' });
        assert.deepEqual(await fileManager.locator('.suggestion-item').allTextContents(), ['/srv/www/.well-known']);
        await page.keyboard.press('Escape');
        await fileManager.locator('.path-input').waitFor({ state: 'detached' });
        assert.equal(await fileManager.isVisible(), true);
        const typePath = async value => {
            await fileManager.locator('.address-bar').click();
            await fileManager.locator('.path-input').fill(value);
            await page.keyboard.press('Enter');
        };
        await typePath('/srv/www/missing.txt');
        await page.getByText('No such file').waitFor();
        await typePath('/srv/www/nginx.conf');
        const typedEditor = page.locator('[data-floating-windows] .file-editor-window');
        await typedEditor.locator('.monaco-editor').waitFor();
        await typedEditor.getByRole('button', { name: 'Close', exact: true }).click();
        await typedEditor.waitFor({ state: 'detached' });
        const previews = page.locator('[data-floating-windows] .file-preview-window');
        const box = async locator => locator.boundingBox();
        const zIndex = locator => locator.evaluate(el => Number(el.style.zIndex));
        await fileItem('architecture.svg').click();
        // the diagram is 640 px wide
        const image = previews.first().locator('img');
        await page.waitForFunction(() => document.querySelector('.file-preview-window img')?.complete);
        await previews.first().getByRole('slider', { name: 'Zoom' }).fill('200');
        assert.equal(Math.round((await image.boundingBox()).width), 1280);
        const imageView = previews.first().locator('.preview-content');
        const scrollLeft = () => imageView.evaluate(el => Math.round(el.scrollLeft));
        const centered = await scrollLeft();
        assert.ok(centered > 0, 'zooming keeps the middle of the image in view');
        const viewBox = await imageView.boundingBox();
        await page.mouse.move(viewBox.x + viewBox.width / 2, viewBox.y + viewBox.height / 2);
        await page.mouse.down();
        await page.mouse.move(viewBox.x + viewBox.width / 2 - 120, viewBox.y + viewBox.height / 2, { steps: 4 });
        await page.mouse.up();
        assert.equal(await scrollLeft(), centered + 120, 'a zoomed image is moved by dragging it');
        await previews.first().getByRole('button', { name: 'Fit to window', exact: true }).click();
        assert.ok((await image.boundingBox()).width <= 640);
        const firstStart = await box(previews.first());
        const header = await box(previews.first().locator('.floating-window-header'));
        await page.mouse.move(header.x + 100, header.y + 20);
        await page.mouse.down();
        await page.mouse.move(header.x + 700, header.y + 420, { steps: 5 });
        await page.mouse.up();
        await nextFrame();
        const firstMoved = await box(previews.first());
        assert.ok(firstMoved.x > firstStart.x && firstMoved.y > firstStart.y, 'preview window is draggable');
        await fileItem('topology.svg').click();
        await previews.nth(1).waitFor();
        const secondStart = await box(previews.nth(1));
        assert.deepEqual([secondStart.x - firstStart.x, secondStart.y - firstStart.y], [32, 32]);
        assert.ok(await zIndex(previews.nth(1)) > await zIndex(previews.first()));
        await page.mouse.click(firstMoved.x + firstMoved.width - 160, firstMoved.y + 20);
        assert.ok(await zIndex(previews.first()) > await zIndex(previews.nth(1)), 'clicking a window raises it');
        await previews.nth(1).getByRole('button', { name: 'Close', exact: true }).click();
        assert.equal(await previews.count(), 1);
        await fileItem('nginx.conf').click();
        const editor = page.locator('[data-floating-windows] .file-editor-window');
        await editor.locator('.monaco-editor').waitFor();
        await editor.locator('.view-lines').click();
        await page.keyboard.type('# reviewed');
        await editor.locator('.modified-indicator').waitFor();
        await page.keyboard.press('Control+A');
        await page.keyboard.press('Tab');
        await page.keyboard.press('Escape');
        assert.equal(await fileManager.locator('.file-item.selected').count(), 0);
        assert.equal(await page.evaluate(() => Boolean(document.activeElement.closest('.file-editor-window'))), true);
        assert.equal(await fileManager.isVisible(), true);
        await page.screenshot({ path: 'artifacts/v2/file-windows.png' });
        await editor.getByRole('button', { name: 'Close', exact: true }).click();
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        await editor.waitFor({ state: 'detached' });
        const listedFiles = async () => (await fileManager.locator('.file-item h2').allTextContents()).filter(name => /\.(svg|sh|conf)$/.test(name));
        assert.deepEqual(await listedFiles(), ['architecture.svg', 'deploy.sh', 'nginx.conf', 'topology.svg']);
        await fileManager.getByRole('button', { name: 'Sort by Size' }).click();
        assert.deepEqual(await listedFiles(), ['nginx.conf', 'architecture.svg', 'topology.svg', 'deploy.sh']);
        await fileManager.getByRole('button', { name: 'Size, sorted descending' }).click();
        assert.deepEqual(await listedFiles(), ['deploy.sh', 'topology.svg', 'architecture.svg', 'nginx.conf']);
        await fileManager.getByRole('button', { name: 'Sort by Name' }).click();
        assert.match(await fileManager.locator('.file-item .file-date').first().textContent(), /\d{1,2}:\d{2}/);
        await fileItem('nginx.conf').click({ button: 'right' });
        await page.getByRole('menuitem', { name: 'Copy path', exact: true }).click();
        await page.getByText('Copied to clipboard').first().waitFor();
        await fileManager.locator('.floating-window-header').getByRole('button', { name: 'Close', exact: true }).click();
        await fileManager.waitFor({ state: 'detached' });
        await page.locator('.workspace-global-nav').getByRole('link', { name: 'Settings', exact: true }).click();
        await page.locator('.administration-index').waitFor();
        assert.equal(await previews.first().isVisible(), false);
        await page.locator('.workspace-global-nav').getByRole('link', { name: 'Workspace', exact: true }).click();
        await previews.first().getByRole('button', { name: 'Close', exact: true }).click();
        await previews.first().waitFor({ state: 'detached' });
        await page.locator('.server-tab').first().click({ button: 'right' });
        await page.getByRole('menuitem', { name: 'File manager', exact: true }).click();
        await fileItem('assets').click({ button: 'right' });
        const terminalHere = page.waitForRequest(r => r.url().endsWith('/api/connections') && r.method() === 'POST');
        await page.getByRole('menuitem', { name: 'Open terminal here', exact: true }).click();
        assert.equal((await terminalHere).postDataJSON().startPath, '/srv/www/assets');
        await fileManager.waitFor({ state: 'detached' });
        await page.locator('.xterm').first().waitFor();
        fixture.liveConnections = []; fixture.connectionSucceeds = false;
        await page.setViewportSize({ width: 1600, height: 1000 });
        await page.goto(baseURL + '/audit');
        await page.getByRole('button', { name: 'Replay session recording' }).first().click();
        await page.getByRole('button', { name: 'Play recording', exact: true }).click();
        await page.locator('.recording-display-area').getByText('systemctl status nginx', { exact: false }).waitFor();
        await page.getByRole('button', { name: 'Pause recording', exact: true }).click();
        await page.getByRole('button', { name: 'Play recording', exact: true }).waitFor();
        await page.screenshot({ path: 'artifacts/v2/recording-replay.png', fullPage: true });
        await page.keyboard.press('Escape');
        await page.locator('.recording-player-content').waitFor({ state: 'hidden' });
        await page.getByRole('button', { name: 'Replay session recording' }).first().click();
        await page.getByRole('button', { name: 'Play recording', exact: true }).waitFor();
        await page.keyboard.press('Escape');
        await page.locator('.recording-player-content').waitFor({ state: 'hidden' });
        await page.getByRole('button', { name: 'Replay session recording' }).nth(1).click();
        await page.getByRole('button', { name: 'Play recording', exact: true }).click();
        await page.getByRole('button', { name: 'Pause recording', exact: true }).waitFor();
        await page.keyboard.press('Escape');
        await page.locator('.recording-player-content').waitFor({ state: 'hidden' });
        await page.getByRole('button', { name: 'Details', exact: true }).first().click();
        const expanded = page.locator('.row-expanded');
        assert.equal(await expanded.locator('h4', { hasText: 'Connection reason' }).locator('xpath=following-sibling::p').textContent(), 'CHG-4182 nginx upgrade');
        assert.equal(await expanded.getByText('connection reason:').count(), 0);
        const auditFilter = label => page.locator('.filter-group').filter({ has: page.getByText(label, { exact: true }) }).locator('.select-box__selected');
        const connectionLogs = page.waitForRequest(r => r.url().includes('/api/audit/logs?') && r.url().includes('category=connections'));
        await auditFilter('Activity').click();
        await page.locator('.select-box__option', { hasText: 'Server connections' }).click();
        await connectionLogs;
        await page.locator('.audit-row').nth(3).waitFor();
        assert.deepEqual([...new Set(await page.locator('.audit-row .cell.action small').allTextContents())], ['Server connections']);
        assert.equal(await page.locator('.audit-row .cell.action span', { hasText: 'SSH connection' }).count(), 2);
        await auditFilter('Action').click();
        await page.locator('.select-box__option').first().waitFor();
        assert.deepEqual(await page.locator('.select-box__option').allTextContents(),
            ['All actions', 'SSH connection', 'SFTP connection', 'Proxmox connection', 'RDP connection', 'VNC connection',
                'Telnet connection', 'Session shared', 'Sharing stopped', 'Share permissions changed']);
        await page.keyboard.press('Escape');
        const download = page.waitForEvent('download');
        const exported = page.waitForRequest(r => r.url().includes('/api/audit/export?'));
        await page.getByRole('button', { name: 'Export CSV' }).click();
        const exportUrl = (await exported).url();
        assert.ok(exportUrl.includes('category=connections') && !exportUrl.includes('limit='), exportUrl);
        assert.equal((await exported).headers().authorization, 'Bearer fixture-token', 'the token is sent as a header, not in the URL');
        assert.match((await download).suggestedFilename(), /^infra-w-audit-\d{4}-\d{2}-\d{2}\.csv$/);
        await page.getByLabel('Keep entries').click();
        await page.getByRole('option', { name: '1 year', exact: true }).click();
        await page.getByText('Keep audit entries for 1 year?', { exact: false }).waitFor();
        const retentionSaved = page.waitForRequest(r => r.url().endsWith('/api/settings') && r.method() === 'PATCH');
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        assert.deepEqual((await retentionSaved).postDataJSON(), { auditRetentionDays: 365 });
        await page.getByText('Audit entries are kept for: 1 year.').waitFor();
        fixture.user.role = 'user';
        await page.goto(baseURL + '/settings/authentication');
        await page.getByRole('alert').waitFor();
        assert.equal(await page.getByRole('button', { name: 'Add LDAP', exact: true }).count(), 0);
        const openOrganization = async () => {
            await page.goto(baseURL + '/settings/organizations');
            await page.locator('.org-toggle', { hasText: 'Operations' }).click();
            await page.locator('.org-detail').waitFor();
        };
        await openOrganization();
        assert.equal(await page.getByText('Audit settings', { exact: true }).count(), 0);
        fixture.user.role = 'admin';
        await openOrganization();
        await page.getByText('Audit settings', { exact: true }).click();
        await page.locator('.organization-audit-settings').waitFor();
        await page.getByRole('button', { name: 'Edit organization' }).click();
        await page.getByLabel('Name', { exact: true }).fill('Operations Zurich');
        const renamed = page.waitForRequest(r => r.url().endsWith('/api/organizations/1') && r.method() === 'PATCH');
        await page.getByRole('button', { name: 'Save', exact: true }).click();
        assert.deepEqual((await renamed).postDataJSON(), { name: 'Operations Zurich', description: null });
        await page.getByRole('tab', { name: 'Members' }).click();
        const promoted = page.waitForRequest(r => r.url().endsWith('/api/organizations/1/members/2') && r.method() === 'PATCH');
        await page.getByRole('button', { name: 'Make Jana Keller a manager' }).click();
        assert.deepEqual((await promoted).postDataJSON(), { role: 'manager' });
        await page.getByRole('button', { name: 'Make Jana Keller a member' }).waitFor();
        assert.equal(await page.getByRole('button', { name: 'Transfer the ownership to Jana Keller' }).count(), 1);
        await page.goto(baseURL + '/settings/integrations');
        await page.getByRole('button', { name: 'Edit', exact: true }).first().click();
        await page.locator('.integration-sync-status').getByText('Imported 42 devices and 18 virtual machines').waitFor();
        await page.getByRole('button', { name: 'Preview sync', exact: true }).click();
        await page.getByText('A sync would create 1, update 5 and remove 2 servers.').waitFor();
        assert.equal(await page.getByRole('button', { name: 'Apply 2 removals' }).count(), 1);
        await page.keyboard.press('Escape');
        await page.locator('.integration-dialog').waitFor({ state: 'detached' });
        await page.goto(baseURL + '/snippets');
        await page.getByRole('searchbox', { name: 'Search name, description or code' }).fill('ss -t');
        await page.locator('.command-row').nth(1).waitFor({ state: 'detached' });
        assert.deepEqual(await page.locator('.command-row strong').allTextContents(), ['Listening ports']);
        await page.getByRole('tab', { name: 'Scripts' }).click();
        await page.getByRole('searchbox', { name: 'Search name, description or code' }).fill('');
        await page.getByRole('button', { name: 'Run Patch host on a host' }).click();
        assert.deepEqual(await page.locator('.command-picker__item h4').allTextContents(), ['edge-zrh-01', 'core-db-01', 'build-runner-04', 'backup-node-01']);
        const scriptRun = page.waitForRequest(r => r.url().endsWith('/api/connections') && r.method() === 'POST');
        await page.locator('.command-picker__item', { hasText: 'core-db-01' }).click();
        const runBody = (await scriptRun).postDataJSON();
        assert.deepEqual([runBody.entryId, runBody.identityId, runBody.scriptId], [2, 1, 1]);
        await page.getByRole('heading', { name: 'Infrastructure access' }).waitFor();
        await page.goto(baseURL + '/settings/authentication');
        await page.getByLabel('Sign out after inactivity').fill('8');
        const settingsSaved = page.waitForRequest(r => r.url().endsWith('/api/settings') && r.method() === 'PATCH');
        await page.getByRole('button', { name: 'Save', exact: true }).click();
        assert.deepEqual((await settingsSaved).postDataJSON(), { sessionIdleHours: 8, sessionMaxDays: 30 });
        await page.goto(baseURL + '/settings/hostKeys');
        const changedKey = page.locator('.settings-list-item').first();
        await changedKey.getByText('Key changed').waitFor();
        assert.match(await changedKey.textContent(), /10\.24\.2\.21:22.*core-db-01/);
        await changedKey.getByRole('button', { name: 'Accept new key' }).click();
        const accepted = page.waitForRequest(r => r.url().endsWith('/api/host-keys/2/accept'));
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        await accepted;
        await page.getByText('Key changed').waitFor({ state: 'detached' });
        await page.goto(baseURL + '/settings/apiTokens');
        await page.getByRole('button', { name: 'Create token' }).click();
        await page.getByLabel('Name', { exact: true }).fill('CI inventory');
        const createdToken = page.waitForRequest(r => r.url().endsWith('/api/tokens') && r.method() === 'PUT');
        await page.getByRole('button', { name: 'Create', exact: true }).click();
        assert.deepEqual((await createdToken).postDataJSON(), { name: 'CI inventory', scope: 'read', days: 90 });
        await page.getByText('infw_Fx7q2mZfixtureOnlyTokenValueNotReal0123456789').waitFor();
        await page.getByRole('button', { name: 'Done', exact: true }).click();
        await page.locator('.settings-list-item', { hasText: 'CI inventory' }).getByText('Read only').waitFor();
        await page.goto(baseURL + '/settings/notifications');
        await page.getByLabel('Webhook URL').fill('https://ntfy.example.com/infra-w');
        await page.getByText('A scheduled backup failed', { exact: true }).click();
        const savedNotifications = page.waitForRequest(r => r.url().endsWith('/api/settings/notifications') && r.method() === 'PATCH');
        await page.getByRole('button', { name: 'Save', exact: true }).click();
        assert.deepEqual((await savedNotifications).postDataJSON(), { webhookUrl: 'https://ntfy.example.com/infra-w', webhookEvents: ['backup.failed'] });
        await page.getByRole('button', { name: 'Send test' }).click();
        await page.getByText('The webhook accepted the test notification.').waitFor();
        await page.goto(baseURL + '/settings/account');
        await page.getByRole('button', { name: 'Change password' }).click();
        await page.getByLabel('Current password').waitFor();
        await page.getByLabel('New password', { exact: true }).fill('short');
        await page.getByLabel('Confirm new password').fill('short');
        await page.locator('.password-change').getByRole('button', { name: 'Change password' }).click();
        await page.getByText('The new password must have at least 12 characters.').waitFor();
        await page.keyboard.press('Escape');
        await page.goto(baseURL + '/settings');
        const release = page.getByRole('link', { name: `INFRA-W v${version} Release notes on GitHub` });
        assert.equal(await release.getAttribute('href'), `https://github.com/swissmakers/infra-w/releases/tag/v${version}`);
        await page.locator('.settings-navigation-footer').getByText(`INFRA-W v${version}`).waitFor();
        await page.goto(baseURL + '/settings/users');
        const devices = page.locator('.settings-section', { has: page.getByRole('heading', { name: 'Signed-in devices' }) }).locator('.settings-list-item');
        await devices.nth(1).waitFor();
        assert.match(await devices.nth(1).textContent(), /Jana Keller · Chrome 129.0.0.0 on Windows 10/);
        await devices.filter({ hasText: 'Jana Keller' }).getByRole('button', { name: 'Sign out' }).click();
        await page.getByText('The device was signed out.').waitFor();
        await devices.filter({ hasText: 'Jana Keller' }).waitFor({ state: 'detached' });
        assert.equal(await devices.count(), 1);
        await page.getByRole('button', { name: 'Actions' }).nth(1).click();
        assert.equal(await page.getByText('Reset two-factor authentication').count(), 1, 'j.keller has a passkey');
        await page.getByText('Lock account').click();
        await page.getByText('Lock j.keller?', { exact: false }).waitFor();
        const locked = page.waitForRequest(r => r.url().endsWith('/api/users/2/lock'));
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        assert.deepEqual((await locked).postDataJSON(), { locked: true });
        const kellerLocked = page.locator('.user-cell', { hasText: 'Jana Keller' }).getByText('Locked', { exact: true });
        await kellerLocked.waitFor();
        await page.screenshot({ path: 'artifacts/v2/users-admin.png', fullPage: true });
        await page.getByRole('button', { name: 'Actions' }).nth(1).click();
        assert.equal(await page.getByText('Login as user').count(), 0);
        await page.getByText('Unlock account').click();
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        await kellerLocked.waitFor({ state: 'detached' });
        await page.getByRole('button', { name: 'Actions' }).nth(1).click();
        await page.getByText('Login as user').click();
        await page.getByText('Sign in as j.keller?', { exact: false }).waitFor();
        await page.getByRole('button', { name: 'Confirm', exact: true }).click();
        await page.getByText('You are working as Jana Keller on behalf of Alex Morgan.').waitFor();
        const loggedOut = page.waitForRequest(r => r.url().endsWith('/api/auth/logout'));
        await page.getByRole('button', { name: 'Return to my account' }).click();
        assert.equal((await loggedOut).postDataJSON().token, 'impersonation-token');
        await page.locator('.impersonation-banner').waitFor({ state: 'detached' });
        await page.getByRole('heading', { name: 'Infrastructure access' }).waitFor();
        assert.equal(await page.evaluate(() => localStorage.getItem('overrideToken')), null);
        await page.goto(baseURL + '/settings');
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('.administration-index').waitFor();
        await page.screenshot({ path: 'artifacts/v2/administration-mobile.png', fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        await page.goto(baseURL + '/servers');
        await page.getByRole('heading', { name: 'Infrastructure access' }).waitFor();
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: 'artifacts/v2/workspace-mobile.png', fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        fixture.recentFails = true;
        await page.reload();
        await page.getByText('Recent connections could not be loaded.').waitFor();
        fixture.recentFails = false;
        await page.getByRole('button', { name: 'Try again', exact: true }).click();
        await page.getByText('Recent connections could not be loaded.').waitFor({ state: 'hidden' });
        fixture.inventory = [];
        await page.reload();
        await page.getByRole('heading', { name: 'Start with your infrastructure' }).waitFor();
        fixture.signedIn = false;
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await page.getByText('Sign in to your infrastructure workspace.').waitFor();
        assert.equal(await page.evaluate(() => document.documentElement.dataset.theme), 'light');
        await page.emulateMedia({ colorScheme: 'dark' });
        await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
        await page.screenshot({ path: 'artifacts/v2/login-mobile.png', fullPage: true });
        assert.deepEqual(errors, []);
        console.log('Browser smoke passed: inventory overview, narrowing search, connection errors, web-only navigation, LDAP presets, draft tests, modal focus and dirty confirmation, account preferences, terminal customization, movable file manager, suggestions, typed file paths, image zoom and panning, floating windows and open terminal here, live terminal persistence across administration, themes, navigation, NetBox dialog with sync status and preview, share link lifetime, sign-in prompts and failure reasons, member roles, host keys, API tokens, webhook notifications, file sorting and copy path, organization rename, snippet search and running a script on a chosen host, terminal and desktop recording playback/reopen, audit connection reasons, activity filter, CSV export and retention, administrator-only audit settings, installed version, device sign-out and account lock, session lifetime, password rules, "Login as" with banner, mobile, retry, empty state and login following the system theme.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
